1.0.9
HexxyCraft/modpack pull request #91
Opened 2023-05-28 23:30 UTC by object-Object

Checklist:
- [x] Bumped `pack.toml` version number (if merging to `master`)
- [x] Ran installer with `-s both` to ensure server-only mods work
- [x] Ran `packwiz refresh` just before final commit

/schedule

2023-05-28 23:30 UTC, object-Object commented
:hourglass: **Merge Schedule**
Scheduled to be merged the next time the merge action is scheduled via the cron expressions
<!-- Merge Schedule Pull Request Comment -->

2023-05-29 01:35 UTC, LlamaSageR requested changes
Auto-detect for Jars and Cages causes unintended consequences, since it simply checks what the size of the entity is. This allows the capture of unintended entities, such as Baby Zombies. The whitelist should be fine itself, without the auto-detect.

2023-05-29 01:37 UTC, object-Object commented
Should be resolved with 0c21b02.

2023-05-29 01:45 UTC, LlamaSageR approved these changes

2023-05-29 02:49 UTC, merged